### ISSUE TITLE
API endpoints shouldn't be exposed in the config file

### ISSUE THREAD

**Issue by doublerr** [kumoru/kumoru-sdk-go#7]
I don't believe there is a reason for a normal user to change the API endpoints they are using. As such, I believe we should remove them from the config file and default them in the code. However we should still  attempt to read the values from the file so that we have the ability to override them for the bootstrap process, hitting staging, etc.

**Comment by dubsquared** [comment]
Seems like a slippery slope since each customer is going to have a unique application manager (AM) URL.  Secondly, if they have more than one pool, how do we discern one AM from the other?  I think in code, file, and command line override are all useful in their own respect.

**Comment by doublerr** [comment]
Once AM is ripped out, there is only 1. There will not be one per customer
